# Audited adapter for the team's mixed host-tools / ARM64-rootfs SDK image.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
include(/opt/Cross-Compilation/env_arm.cmake)
set(CMAKE_LIBRARY_ARCHITECTURE aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# /opt/ros and /usr/lib/aarch64-linux-gnu are already target prefixes in this SDK.
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
list(PREPEND CMAKE_LIBRARY_PATH /usr/lib/aarch64-linux-gnu /usr/aarch64-linux-gnu/lib)
list(PREPEND CMAKE_PREFIX_PATH /opt/ros/humble /opt/third_party/json-3.10.5 /opt/third_party/yaml-cpp-0.7.0 /opt/third_party/spdlog-1.9.2 /opt/third_party/console_bridge-1.0.2 /opt/third_party/tinyxml2-9.0.0)
set(PYTHON_EXECUTABLE /usr/bin/python3 CACHE FILEPATH "Host message generator")
set(Python3_EXECUTABLE /usr/bin/python3 CACHE FILEPATH "Host message generator")
set(PYTHON_INCLUDE_DIR /usr/include/python3.10 CACHE PATH "Common Python headers")
set(PYTHON_LIBRARY /usr/lib/aarch64-linux-gnu/libpython3.10.so CACHE FILEPATH "Target Python library")
set(PYTHON_SOABI cpython-310-aarch64-linux-gnu CACHE STRING "Observed target rclpy ABI")
set(SQLite3_INCLUDE_DIR /usr/include CACHE PATH "Jammy SQLite headers")
set(SQLite3_LIBRARY /usr/lib/aarch64-linux-gnu/libsqlite3.so.0 CACHE FILEPATH "Target SQLite runtime")
set(OPENSSL_ROOT_DIR /opt/third_party/openssl-3.0.2 CACHE PATH "Target OpenSSL")
set(OPENSSL_INCLUDE_DIR /opt/third_party/openssl-3.0.2/include CACHE PATH "Target OpenSSL headers")
set(OPENSSL_SSL_LIBRARY /opt/third_party/openssl-3.0.2/lib/libssl.so CACHE FILEPATH "Target TLS")
set(OPENSSL_CRYPTO_LIBRARY /opt/third_party/openssl-3.0.2/lib/libcrypto.so CACHE FILEPATH "Target crypto")
# Never leave build/SDK paths in deployment binaries. Environment supplies ROS/SDK runtime paths.
set(CMAKE_INSTALL_RPATH "")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE)
# Humble copies generator_py support libraries into the Python package from the
# build tree. Install-only RPATH settings do not sanitize those copies.
set(CMAKE_SKIP_RPATH TRUE CACHE BOOL "No build or install RPATH in deployable libraries" FORCE)
set(jsoncpp_DIR /opt/third_party/jsoncpp-1.9.5/lib/cmake/jsoncpp CACHE PATH "ARM64 JsonCpp config" FORCE)
